### ISSUE TITLE
Arm64 arch not usable (Apple M1 chips)

### ISSUE THREAD

**Issue by sergioisidoro** [liquibase/docker#126]
Due to a qemu upstream bug, this container is not usable in arm64 archs with x86 emulation, with the following outcome:

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
``` 

Building this image locally in an arm64 machine works perfectly, without any major compatibility issues.

There's not much hopes of getting the bug fixed, with most support being:

> Please encourage the author of this container to supply an arm64 or multi-arch image, not just an Intel one

Please consider building this image in arm64 architectures in the near future. Especially now that M1 looks to be the mainstream Apple platform for new machines.

**Comment by ap-liquibase** [comment]
dev team will evaluate what might be required to produce/maintain an arm64 image longterm

**Comment by sfat** [comment]
Maybe this is not the way to go and I'm hoping for this to be fixed in the near future, but for anyone struggling to run this on Arm (M1), I've forked this repository and pushed both amd64 and arm64 images until this is closed. You can find the docker images [here](https://hub.docker.com/r/sfat/liquibase) 
forked repo: https://github.com/sfat/liquibase-docker (just created a bash script to build these images)

**Comment by fernandomoraes** [comment]
thank you @sfat

**Comment by erinlkolp** [comment]
Thanks so much, @sfat ! :)

**Comment by kdubrovnyi** [comment]
> dev team will evaluate what might be required to produce/maintain an arm64 image longterm

hi guys, any progress on this? it's been almost a year...

**Comment by sabatinim** [comment]
> Maybe this is not the way to go and I'm hoping for this to be fixed in the near future, but for anyone struggling to run this on Arm (M1), I've forked this repository and pushed both amd64 and arm64 images until this is closed. You can find the docker images [here](https://hub.docker.com/r/sfat/liquibase) forked repo: https://github.com/sfat/liquibase-docker (just created a bash script to build these images)

Great! It works perfectly! No more stops during local building! I don't know why official images doesn't have ARM support (Mac M1)

**Comment by karthik-kunjithapatham** [comment]
Thank you @sfat

**Comment by mossad-zika** [comment]
@ap-liquibase hello, I am wondering if the "dev team" is still with us

**Comment by jnewton03** [comment]
@mossad-zika Thank you for bringing this back to our attention.  Right now we're using Docker Hub Autobuilds and it looks like it isn't straightforward to create the arm64 images.  I'll take a look at an alternative build method based on @sfat 's fork.

**Comment by sfat** [comment]
@jnewton03,
First of all, I'm really happy that you are taking the time to look into this.

I've also looked into Docker Hub Automated Builds and it's true that at the moment, Docker Hub does not support arm based builds.

You can take a look at my fork, but I would rather suggest taking a look at doing this via Github actions, it will be automated and everything.

Is it mandatory for you to run the builds via Docker Hub or could it be an option to switch the builds via Github Actions? Why I'm asking is it then would make the docker images from one place instead of one via Docker Hub and the other architectures on another place.

The other option, what I've quickly looked up, a possibility to create some hooks for the Dockerfile and make use of QEMU to do the builds on other architectures. I'm not really a fan, but whatever works for you and making the arm based image an official variant, would be awesome.

Do let me know if you want any help with this in anyway, I'm happy to give a hand.

**Comment by nvoxland** [comment]
Thanks, @sfat, any help is always appreciated!

We are wanting to move off the docker-hub based builds to github actions. We've been switching our other repos to use that, but haven't gotten to the docker repo yet. We'd need something `on publish` that ends up pushing both the full version, plus just the 1st two digits of the version, plus "latest" for all the architectures.

The bulk of the logic is really just:
```yaml
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ...
```
right? With a previous call to log into docker hub, and logic to create the list of tags based on version being published?

Anything more we have to worry about? Any chance you have or could do a starting github action in a PR for us?
