### ISSUE TITLE
Relative vs Absolute Path for changeLogFile

### ISSUE THREAD

**Issue by RafaelWO** [liquibase/docker#61]
The REAMDE states the following "Complete Example":

> **Using a properties file**
> liquibase.docker.properties file:
> 
> classpath: /liquibase/changelog
> url: jdbc:postgresql://<IP OR HOSTNAME>:5432/<DATABASE>?currentSchema=<SCHEMA NAME>
> changeLogFile: changelog.xml
> username: <USERNAME>
> password: <PASSWORD>
> liquibaseProLicenseKey=\<PASTE LB PRO LICENSE KEY HERE>
>
> CLI: docker run --rm -v <PATH TO CHANGELOG DIR>:/liquibase/changelog liquibase/liquibase --defaultsFile=/liquibase/changelog/liquibase.docker.properties update

If configured like that, the `changelog.xml` ends up within the container filesystem `/liquibase/changelog.xml` instead of the mounted directory `/liquibase/changelog` when running `generateChangeLog`. See [my StackOverflow post](https://stackoverflow.com/q/67277878/9478384) plus [answer](https://stackoverflow.com/a/67281485/9478384) for details.

It works when I specidy the absolute path of `changelog.xml`:
```
classpath: /liquibase/changelog
url: jdbc:postgresql://localhost:5432/mydb?currentSchema=public
changeLogFile: /liquibase/changelog/changelog.xml
username: myuser
password: mypass
```

Is this an issue of the README (then I can create a PR) or a "deeper" problem i.e. the usage from above should actually work as intended?

**Comment by RafaelWO** [comment]
### Update
Although using the absolute path with `generateChangeLog`, e.g. `update` fails now:
~~~
Starting Liquibase at 12:42:17 (version 4.3.3 #52 built at 2021-04-12 17:08+0000)
Unexpected error running Liquibase: The file /liquibase/changelog/salk-ehr-changelog.xml was not found in
    - /liquibase/changelog
Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.
~~~

What Am I supposed to use now? Relative or Absolute?

**Comment by r2liquibase** [comment]
Hi, @RafaelWO . Getting some folks to review this issue.

**Comment by szandany** [comment]
Hi @RafaelWO,

I believe that we need to be more specific in the README file when showing the example with the defaultsFile (liquibase.properties).
We cannot assume that the changelog will already be in the classpath since we don't know how the changelog is being referenced in the properties file.
**Here is my suggestion:**
Instead of having the example:
`docker run --rm -v c:\projects\my-project\src\main\resources:/liquibase/changelog --defaultsFile=/liquibase/changelog/liquibase.properties update`

We can be more intentional about the chanelog location locally and mount it in as well.  Also, reference the changelog and the properties file with a **relative path**.
For example:
`docker run --rm -v /path/to/project/resources/:/liquibase/changelog: liquibase/liquibase --changeLogFile=./changelog/myChangeLog.xml --defaultsFile=./changelog/liquibase.properties update`

@RafaelWO, please try my suggestion and see if this works for you.

**Comment by nvoxland** [comment]
I put an answer in your stackoverflow question.

Making the changeLogFile absolute for update is wrong because that will cause you heartache down the road. And, even though adding "./changelog" to the changeLogFile is not an absolute file, it is going to cause the same heartache down the road.

Your initial guess of specifying a different path for generateChangeLog only was correct. What was the generateChangeLog command you ran that ended up not saving it to a spot where `update` could read it?

**Comment by RafaelWO** [comment]
@szandany 
>We can be more intentional about the chanelog location locally and mount it in as well. Also, reference the changelog and the properties file with a relative path.

I'm not sure whether that's a good idea because (1) it is never used that way in the examples and (2) nobody knows the internal structure of docker image (except when debugging it), i.e. that internally `/liquibase` is working dir.

But your example would probably also _work_.

**Comment by RafaelWO** [comment]
@nvoxland 
Thanks for answering on stackoverflow; I appreciate that!

> Making the changeLogFile absolute for update is wrong

Yeah that makes sense to me. I ended up doing it only for `generateChangeLog`.

>What was the generateChangeLog command you ran that ended up not saving it to a spot where update could read it?

It was exactly how I described it in my stackoverflow question (and answer):
```
docker run --rm --net="host" -v <PATH TO CHANGELOG DIR>:/liquibase/changelog liquibase/liquibase --defaultsFile=/liquibase/changelog/liquibase.docker.properties generateChangeLog
```
with the defaults file
```
classpath: /liquibase/changelog
url: jdbc:postgresql://localhost:5432/mydb?currentSchema=public
changeLogFile: changelog.xml
username: myuser
password: mypass
```
In this case the file was not written to the mounted changelog dir but into the working dir of the docker image.

**Comment by nvoxland** [comment]
Sounds like you have it straightened out and this issue can be closed?

**Comment by RafaelWO** [comment]
In general, yes.

But I would be happy if the README (and doc on docker hub) would be extended with a note regarding passing the absolute path when running commands that write files. I would prepare a PR for this if you dont mind?

**Comment by r2liquibase** [comment]
I merged in your PR, @RafaelWO . Closing this issue.

**Comment by mapuga** [comment]
Hello, i'm using github actions with liquibase, i have trying take a file in my repository but when i try excecute liquibase --changeLogFile="${FILESCRPT}" update is like FILESCRPT is empty. Finaly the console show me the same error:
Unexpected error running Liquibase: The file /LQBase/liquibase-4.6.2/propecdn/script.sql was not found in
    - /LQBase/liquibase-4.6.2/lib/mysql-connector-java-8.0.25.jar
    - /LQBase/liquibase-4.6.2/propecdn/.
Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.

Any suggest? pls
